"""Which mesh each piece of street dressing wears — shared, pure, no Unreal.

These tables were originally constants inside
``ldyf.unreal.ldyf_dressing_editor``, which imports ``unreal`` and therefore
cannot be read outside the editor. The verifier needs exactly the same tables
to assert that a signal wears a signal mesh, so they live here and both sides
import them: one definition, no chance of the spawner and the checker drifting
apart and agreeing on a lie.
"""

from __future__ import annotations

DRESSING_ASSETS_VERSION = "dressing_assets_v1"

MARK_PREFIX = "LD_Mark"
CROSSWALK_PREFIX = "LD_Crosswalk"
SIGNAL_PREFIX = "LD_Signal"
TREE_PREFIX = "LD_Tree"
# NOT "LD_TreeBase": every prefix filter here uses str.startswith and
# "LD_Tree" is a prefix of "LD_TreeBase", which would merge the two families.
TREE_BASE_PREFIX = "LD_Pit"
FURNITURE_PREFIX = "LD_Furniture"
CLOSURE_PREFIX = "LD_ClosureProp"

DRESSING_PREFIXES = (MARK_PREFIX, CROSSWALK_PREFIX, SIGNAL_PREFIX,
                     TREE_BASE_PREFIX, TREE_PREFIX, FURNITURE_PREFIX,
                     CLOSURE_PREFIX)

PAINT_COLOURS = {
    "white": (0.92, 0.92, 0.90),
    "yellow": (0.86, 0.66, 0.08),
}

# Only meshes whose material slots all resolve: the StopLight A/C/D/E variants
# each carry one null slot and are excluded (see EVIDENCE prop_probe.json).
SIGNAL_MESH = {
    "traffic_light": "/Game/Prop/Kit_StreetLamp_A/Mesh/SM_StreetLamp_A_StopLight_B",
    "stop_sign": "/Game/Prop/Kit_StopSign_A/Mesh/SM_StopSign_A",
}
# TREES NOW HAVE LEAVES, and the route there is worth recording because four
# earlier attempts did not. Two imported families were eliminated:
#
#   * the City Sample prop kits - branch skeletons of 2.5-5k triangles with no
#     leaf cards at all, by construction;
#   * CitySamplePCG/Megaplants - real Megascans plants with a separate foliage
#     material and 41k-239k triangles, whose LEAF SECTIONS RENDER NOTHING in
#     this project under all four of: the shipped material (which compiles
#     without error and whose textures resolve), Nanite on, Nanite off, and a
#     purpose-authored BLEND_MASKED two-sided material of ours with the _CA
#     texture bound and verified by readback.
#
# The Director closed that path. What works is authoring BOTH halves ourselves:
# geometry generated by ldyf/tree_mesh.py and built through
# StaticMeshDescription, wearing an MSM_TWO_SIDED_FOLIAGE material carrying the
# Kit_Tree_Maple_Red Cap / Cap_Opacity pair. Proven on a single tree, rendered
# and looked at, before any of this was integrated.
#
# The shading model is the part that decides it: under the default lit model a
# backlit leaf card renders as a black silhouette, which is indistinguishable
# from "the leaves did not render" and is what the first test frame showed.
#
# Order is load-bearing: dressing.tree_slots emits variant 0/1/2 and the
# spawner indexes this list by that variant. tree_mesh.TREE_VARIANT_ORDER
# states which shape each index should name, and this list MUST follow it --
# not sorted(TREE_VARIANTS), which puts the narrow columnar where the broad
# street maple belongs.
TREE_MESHES = [
    "/Game/LD/Meshes/SM_LD_Tree_Maple",       # variant 0
    "/Game/LD/Meshes/SM_LD_Tree_Columnar",    # variant 1
    "/Game/LD/Meshes/SM_LD_Tree_Sapling",     # variant 2
]
SHRUB_MESHES = [
    "/CitySamplePCG/Megaplants/Tree_Common_Hazel/Tree_Common_Hazel_01/SM_Common_Hazel_01_B",
]
TREE_BASE_MESH = "/Game/Prop/Kit_TreeBase_A/Mesh/SM_TreeBase_Circle_A"

FURNITURE_MESH = {
    "lamp": ["/Game/Prop/Kit_StreetLamp_A/Mesh/SM_StreetLamp_A_Pole_Large"],
    "bin": ["/Game/Prop/Kit_Trashcan_A/Mesh/SM_Trashcan_A_01"],
    "sign": ["/Game/Prop/Kit_bench_RR/mesh/SM_street_bench",
             "/Game/Prop/Kit_bench_RR/mesh/SM_park_bench_N01"],
}

CLOSURE_MESH = {
    "barricade": "/Game/Prop/Kit_Barricade_A/Mesh/SM_Barricade_A",
    "cone": "/Game/Prop/Kit_ConstructionCone_RR/Mesh/SM_ConstCone_a_N1",
}

TREE_BURY_CM = 10.0        # a street tree's root flare sits just below grade
DECAL_DEPTH_CM = 60.0      # projection depth; deep enough for the kerb camber
