"""Which mesh each piece of street dressing wears — shared, pure, no Unreal.

These tables were originally constants inside
``ldyf.unreal.ldyf_dressing_editor``, which imports ``unreal`` and therefore
cannot be read outside the editor. The verifier needs exactly the same tables
to assert that a signal wears a signal mesh, so they live here and both sides
import them: one definition, no chance of the spawner and the checker drifting
apart and agreeing on a lie.
"""

from __future__ import annotations

from ldyf.tree_mesh import TREE_VARIANT_ORDER

DRESSING_ASSETS_VERSION = "dressing_assets_v1"

MARK_PREFIX = "LD_Mark"
CROSSWALK_PREFIX = "LD_Crosswalk"
SIGNAL_PREFIX = "LD_Signal"
TREE_PREFIX = "LD_Tree"
# NOT "LD_TreeBase": every prefix filter here uses str.startswith and
# "LD_Tree" is a prefix of "LD_TreeBase", which would merge the two families.
TREE_BASE_PREFIX = "LD_Pit"
FURNITURE_PREFIX = "LD_Furniture"
CLOSURE_PREFIX = "LD_ClosureProp"

DRESSING_PREFIXES = (MARK_PREFIX, CROSSWALK_PREFIX, SIGNAL_PREFIX,
                     TREE_BASE_PREFIX, TREE_PREFIX, FURNITURE_PREFIX,
                     CLOSURE_PREFIX)

PAINT_COLOURS = {
    "white": (0.92, 0.92, 0.90),
    "yellow": (0.86, 0.66, 0.08),
}

# Only meshes whose material slots all resolve: the StopLight A/C/D/E variants
# each carry one null slot and are excluded (see EVIDENCE prop_probe.json).
SIGNAL_MESH = {
    "traffic_light": "/Game/Prop/Kit_StreetLamp_A/Mesh/SM_StreetLamp_A_StopLight_B",
    "stop_sign": "/Game/Prop/Kit_StopSign_A/Mesh/SM_StopSign_A",
}
# TREES NOW HAVE LEAVES, and the route there is worth recording because four
# earlier attempts did not. Two imported families were eliminated:
#
#   * the City Sample prop kits - branch skeletons of 2.5-5k triangles with no
#     leaf cards at all, by construction;
#   * CitySamplePCG/Megaplants - real Megascans plants with a separate foliage
#     material and 41k-239k triangles, whose LEAF SECTIONS RENDER NOTHING in
#     this project under all four of: the shipped material (which compiles
#     without error and whose textures resolve), Nanite on, Nanite off, and a
#     purpose-authored BLEND_MASKED two-sided material of ours with the _CA
#     texture bound and verified by readback.
#
# The Director closed that path. What works is authoring BOTH halves ourselves:
# geometry generated by ldyf/tree_mesh.py and built through
# StaticMeshDescription, wearing an MSM_TWO_SIDED_FOLIAGE material carrying the
# Kit_Tree_Maple_Red Cap / Cap_Opacity pair. Proven on a single tree, rendered
# and looked at, before any of this was integrated.
#
# The shading model is the part that decides it: under the default lit model a
# backlit leaf card renders as a black silhouette, which is indistinguishable
# from "the leaves did not render" and is what the first test frame showed.
#
# Order is load-bearing: dressing.tree_slots rolls a variant in {0, 1, 2}
# (``dressing.py``: ``_digest_int(rid + "|tree", 3)``) and the spawner indexes
# this list by that variant, so this list MUST follow
# ``tree_mesh.TREE_VARIANT_ORDER`` -- not ``sorted(TREE_VARIANTS)``, which puts
# the narrow columnar where the broad street maple belongs.
#
# That agreement used to be a convention kept in step by a human. It broke once:
# the two lists drifted, every tree in the city silently wore the wrong shape,
# and every test still passed. It is mechanical now -- TREE_MESHES is DERIVED
# from TREE_VARIANT_ORDER by the rule below, the same rule tools_build_trees.py
# uses to name the meshes it builds (``"SM_LD_Tree_%s" % name.capitalize()``,
# recorded per index in its manifest), so the two cannot disagree.
# ``ldyf/tests/test_tree_variant_order.py`` fails if this derivation is ever
# replaced by a hand-kept copy, or if the order changes in one place only.
TREE_MESH_ROOT = "/Game/LD/Meshes"


def mesh_path_for_variant(variant: str) -> str:
    """Asset path rule: variant ``"maple"`` -> ``/Game/LD/Meshes/SM_LD_Tree_Maple``.

    The asset name comes from the variant name by ``str.capitalize()``, which is
    exactly how ``tools_build_trees.py`` names the mesh it builds for each entry
    of ``TREE_VARIANT_ORDER``, so the derived path is the path that was authored.
    """
    name = str(variant)
    if not name.strip():
        raise ValueError("tree variant name must not be empty")
    return "%s/SM_LD_Tree_%s" % (TREE_MESH_ROOT, name.capitalize())


TREE_MESHES = [mesh_path_for_variant(v) for v in TREE_VARIANT_ORDER]
SHRUB_MESHES = [
    "/CitySamplePCG/Megaplants/Tree_Common_Hazel/Tree_Common_Hazel_01/SM_Common_Hazel_01_B",
]
TREE_BASE_MESH = "/Game/Prop/Kit_TreeBase_A/Mesh/SM_TreeBase_Circle_A"

FURNITURE_MESH = {
    "lamp": ["/Game/Prop/Kit_StreetLamp_A/Mesh/SM_StreetLamp_A_Pole_Large"],
    "bin": ["/Game/Prop/Kit_Trashcan_A/Mesh/SM_Trashcan_A_01"],
    "sign": ["/Game/Prop/Kit_bench_RR/mesh/SM_street_bench",
             "/Game/Prop/Kit_bench_RR/mesh/SM_park_bench_N01"],
}

CLOSURE_MESH = {
    "barricade": "/Game/Prop/Kit_Barricade_A/Mesh/SM_Barricade_A",
    "cone": "/Game/Prop/Kit_ConstructionCone_RR/Mesh/SM_ConstCone_a_N1",
}

TREE_BURY_CM = 10.0        # a street tree's root flare sits just below grade
DECAL_DEPTH_CM = 60.0      # projection depth; deep enough for the kerb camber
